finished project for homework week1
HackYourHomework/Node.js-class40 pull request #12
Opened 2022-11-15 23:20 UTC by anutka2610

2022-11-17 10:05 UTC, AlsasaAmmar requested changes

2022-11-17 10:05 UTC, AlsasaAmmar commented on homework/hackyourtemperature/server.js
> +app.post('/weather', (req, res) => {
add line breaks between your functions as it makes it easier to read the code

2022-11-17 10:05 UTC, AlsasaAmmar commented on homework/hackyourtemperature/server.js
> +app.listen(PORT, () => console.log(`Server is running on ${PORT}`));
it is best practice to leave an empty line at the end of your code (it prevents problems and bugs with compilers)

2022-11-17 10:05 UTC, AlsasaAmmar commented on homework/hackyourtemperature/server.js
> +app.use(express.json());
this line needs to be at line 3.. 
currently, the app is not working because the function 'experss.json()' allows the app to read the json body sent to the server

2022-11-17 10:07 UTC, AlsasaAmmar commented
Good work! 
Just pay more attention to line breaks.. 
Have a look at my comments and see if you need any help

2022-11-18 19:36 UTC, anutka2610 commented
> Good work! Just pay more attention to line breaks.. Have a look at my comments and see if you need any help

thank you. I added changes and have a question. When I refresh page, I have status 304 (network). Is it ok?

2023-01-26 10:19 UTC, closed without merging